
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-5'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object representing identifiers of available items
 *
 * Actor
 *
 * Codename: actor
 * Id: 58099989-319f-495f-aa36-cb3710854e36
 * Codename: actor
 */
export const actorItems = {
    /**
     * Anne Hathaway
     */
    anne_hathaway: {
        codename: 'anne_hathaway',
        id: '04f3fe64-2d62-4db3-84d5-06776c47f543'
    },

    /**
     * Bill Nighy
     */
    bill_nighy: {
        codename: 'bill_nighy',
        id: 'cddc7576-38b3-4de2-9fb9-2d1ce16daa8b'
    },

    /**
     * Billy Crystal
     */
    billy_crystal: {
        codename: 'billy_crystal',
        id: '3e99ea61-7d47-49f0-b271-5757061658ab'
    },

    /**
     * Christian Bale
     */
    christian_bale: {
        codename: 'christian_bale',
        id: 'f0e9e9fa-91e8-40d5-9527-b7e0ae51fc54'
    },

    /**
     * Domhnall Gleeson
     */
    domhnall_gleeson: {
        codename: 'domhnall_gleeson',
        id: 'c37b94d2-56e1-4e0a-9f14-547fe194e0d9'
    },

    /**
     * Jessica Chastain
     */
    jessica_chastain: {
        codename: 'jessica_chastain',
        id: 'a67aacfa-b400-444d-b53e-df1766065034'
    },

    /**
     * Joel Edgerton
     */
    joel_edgerton: {
        codename: 'joel_edgerton',
        id: '3294e4b0-e58b-49d7-85fa-5bc9a86556ec'
    },

    /**
     * Kristen Wiig
     */
    kristen_wiig: {
        codename: 'kristen_wiig',
        id: '2df17777-b347-4590-be05-cb256bf718e9'
    },

    /**
     * Matt Damon
     */
    matt_damon: {
        codename: 'matt_damon',
        id: '69a1cbb3-fcc9-4f50-8631-8298fe106cd5'
    },

    /**
     * Nathalie Boltt
     */
    nathalie_boltt: {
        codename: 'nathalie_boltt',
        id: '11b2170c-6df8-48d6-af66-4ddafa2a425a'
    },

    /**
     * Rachel McAdams
     */
    rachel_mcadams: {
        codename: 'rachel_mcadams',
        id: '10145fa6-b074-4d2e-9a18-07cf23dff33d'
    },

    /**
     * Sharlto Copley
     */
    sharlto_copley: {
        codename: 'sharlto_copley',
        id: 'c10783cb-c8b8-4fec-8f44-7323ffc3227b'
    },

    /**
     * Tom Hardy
     */
    tom_hardy: {
        codename: 'tom_hardy',
        id: 'd1557cb1-d7ec-4d04-9742-f86b52bc34fc'
    }
} as const;
