
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-5'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object representing identifiers of available items
 *
 * Movie
 *
 * Codename: movie
 * Id: b0c0f9c2-ffb6-4e62-bac9-34e14172dd8c
 * Codename: movie
 */
export const movieItems = {
    /**
     *  The Dark Knight Rises
     */
    _the_dark_knight_rises: {
        codename: '_the_dark_knight_rises',
        id: 'e9ff5385-0f10-469a-8525-98189e295c0d'
    },

    /**
     * About Time
     */
    about_time: {
        codename: 'about_time',
        id: 'f5d741ec-e500-4285-97f0-a30196a655bd'
    },

    /**
     * District 9
     */
    district_9: {
        codename: 'district_9',
        id: 'e0b67f90-790c-4509-8679-5ca2df42f3b8'
    },

    /**
     * Monsters, Inc.
     */
    monsters__inc_: {
        codename: 'monsters__inc_',
        id: '00e96c5c-22a2-4ecf-811d-28881d1d2eda'
    },

    /**
     * The Martian
     */
    the_martian: {
        codename: 'the_martian',
        id: 'e9ac3dd7-8129-4f9a-9112-eb24d84d3ecd'
    },

    /**
     * Warrior
     */
    warrior: {
        codename: 'warrior',
        id: '325e2acb-1c14-47f6-af9a-27bc8b6c16fe'
    }
} as const;
