/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const allElementCodenames = [
	"url",
	"first_name",
	"last_name",
	"photo",
	"title",
	"plot",
	"released",
	"length",
	"poster",
	"category",
	"stars",
	"seoname",
	"releasecategory",
] as const;

/*
 * Type representing all element codenames
 */
export type AnyElementCodename = (typeof allElementCodenames)[number];

/*
 * Typeguard for element codename
 */
export function isAnyElementCodename(value: string | undefined | null): value is AnyElementCodename {
	return typeof value === "string" && (allElementCodenames as readonly string[]).includes(value);
}
