/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 *
 * -------------------------------------------------------------------------------
 */

import type { DeliveryClient, DeliveryClientSchema } from "@kontent-ai/delivery-sdk";

/*
 * Schema describing this environment, used to strongly type 'DeliveryClient'
 */
export type CoreClientSchema = DeliveryClientSchema<{
	readonly languageCodenames: readonly ["en", "cz", "German"];
	readonly taxonomies: {
		readonly releasecategory: readonly ["global_release", "us_only", "local_release"];
		readonly movietype: readonly ["student", "tv", "blockbuster", "cinema_only", "film"];
	};
	readonly contentTypes: {
		readonly actor: readonly ["url", "first_name", "last_name", "photo"];
		readonly movie: readonly ["title", "plot", "released", "length", "poster", "category", "stars", "seoname", "releasecategory"];
	};
	readonly collectionCodenames: readonly ["default"];
	readonly workflowCodenames: readonly ["default"];
	readonly workflowStepCodenames: readonly ["draft", "review", "ready_to_publish", "published", "archived", "scheduled"];
}>;

/*
 * Typed delivery client. Use this instead of 'DeliveryClient'
 */
export type CoreDeliveryClient = DeliveryClient<CoreClientSchema>;
