
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0' on 'Wed Feb 12 2020 10:59:47 GMT+0100 (GMT+01:00)'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Movie extends ContentItem {
    public title!: Elements.TextElement;
    public released!: Elements.DateTimeElement;
    public releasecategory!: Elements.TaxonomyElement;
    public seoname!: Elements.UrlSlugElement;
    public length!: Elements.NumberElement;
    public category!: Elements.MultipleChoiceElement;
    public poster!: Elements.AssetsElement;
    public stars!: Elements.LinkedItemsElement<ContentItem>;
    public plot!: Elements.RichTextElement;
}
