
import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Autogenerated by '@kentico/kontent-model-generator@3.2.0' at 'Fri, 08 Oct 2021 09:25:51 GMT'
*/
export type movie = IContentItem<{
    title: Elements.TextElement;released: Elements.DateTimeElement;releasecategory: Elements.TaxonomyElement;seoname: Elements.UrlSlugElement;length: Elements.NumberElement;category: Elements.MultipleChoiceElement;poster: Elements.AssetsElement;stars: Elements.LinkedItemsElement<IContentItem>;plot: Elements.RichTextElement;
}>;
