
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0' on 'Fri Oct 08 2021 10:40:28 GMT+0200 (Central European Summer Time)'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Movie extends ContentItem {
    public title!: Elements.TextElement;
    public released!: Elements.DateTimeElement;
    public releasecategory!: Elements.TaxonomyElement;
    public seoname!: Elements.UrlSlugElement;
    public length!: Elements.NumberElement;
    public category!: Elements.MultipleChoiceElement;
    public poster!: Elements.AssetsElement;
    public stars!: Elements.LinkedItemsElement<ContentItem>;
    public plot!: Elements.RichTextElement;
}
