
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object containing all Language codenames
 */
export const languageValues = ['en', 'cz', 'German'] as const;

/**
 * Type representing Language codenames
 */
export type LanguageCodenames = (typeof languageValues)[number];

/**
 * Type guard for Language codenames
 */
export function isLanguage(value: string | undefined | null): value is LanguageCodenames {
    return typeof value === 'string' && (languageValues as readonly string[]).includes(value);
}
