/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "./_languages.js"

/*
 * Type representing codename of 'cz' language
 */
export type CzLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "cz">

/*
 * Typeguard for codename of 'cz' language
 */
export function isCzLanguageCodename(value: string | undefined | null): value is CzLanguageCodename {
	return typeof value === "string" && value === ("cz" satisfies CzLanguageCodename)
}
