/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from './_languages.js';

/*
 * Type representing codename of entity
 *
 * Name: English
 * Codename: en
 * Type: Language
 */
export type EnglishLanguageCodename = Extract<LanguageCodenames, 'en'>;

/*
 * Type guard for English
 *
 * Name: English
 * Codename: en
 * Type: Language
 */
export function isEnglishLanguageCodename(value: string | undefined | null): value is EnglishLanguageCodename {
	return typeof value === 'string' && value === ('en' satisfies EnglishLanguageCodename);
}
