
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { LanguageCodenames } from './core.language.js';

/**
 * Type representing Language entities
 *
 * Codename: en
 * Id: 00000000-0000-0000-0000-000000000000
 */
export type EnglishLanguage = Extract<LanguageCodenames, 'en'>;

/**
 * Type guard for English entity
 *
 * Codename: en
 * Id: 00000000-0000-0000-0000-000000000000
 */
export function isEnglishLanguage(value: string | undefined | null): value is EnglishLanguage {
    return typeof value === 'string' && value === ('en' satisfies EnglishLanguage);
}
