/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "./_languages.js"

/*
 * Type representing codename of 'English' language
 */
export type EnLanguageCodename = Extract<LanguageCodenames, "en">

/*
 * Typeguard for codename of 'English' language
 */
export function isEnLanguageCodename(value: string | undefined | null): value is EnLanguageCodename {
	return typeof value === "string" && value === ("en" satisfies EnLanguageCodename)
}
