/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "./_languages.js"

/*
 * Type representing codename of 'German' language
 */
export type GermanLanguageCodename = Extract<LanguageCodenames, "German">

/*
 * Typeguard for codename of 'German' language
 */
export function isGermanLanguageCodename(value: string | undefined | null): value is GermanLanguageCodename {
	return typeof value === "string" && value === ("German" satisfies GermanLanguageCodename)
}
