/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from './_languages.js';

/*
 * Type representing codename of German
 *
 * Codename: German
 */
export type GermanLanguageCodename = Extract<LanguageCodenames, 'German'>;

/*
 * Type guard for German entity
 *
 * Codename: German
 */
export function isGermanLanguageCodename(value: string | undefined | null): value is GermanLanguageCodename {
	return typeof value === 'string' && value === ('German' satisfies GermanLanguageCodename);
}
