/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-4'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

export * from './_languages.js';
export * from './czLanguage.language.js';
export * from './enLanguage.language.js';
export * from './germanLanguage.language.js';
