/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { MigrationElementModels } from "@kontent-ai/migration-toolkit"
import type { CoreMigrationItem } from "../migration.js"

/*
 * Actor
 *
 * Codename: actor
 * Id: 58099989-319f-495f-aa36-cb3710854e36
 */
export type ActorItem = CoreMigrationItem<
	"actor",
	{
		/*
		 * Url
		 *
		 * Codename: url
		 * Id: c8658782-f209-a573-9c85-430fb4e3e9f0
		 * Type: url_slug
		 * Required: false
		 */
		readonly url: MigrationElementModels.UrlSlugElement

		/*
		 * First name
		 *
		 * Codename: first_name
		 * Id: 14dd70e5-c42d-f111-9640-c82b443edf1d
		 * Type: text
		 * Required: true
		 * Guidelines: This is the first name of the actor
		 */
		readonly first_name: MigrationElementModels.TextElement

		/*
		 * Last name
		 *
		 * Codename: last_name
		 * Id: 9f7a0dd4-af3a-95ca-0358-400c14ce7075
		 * Type: text
		 * Required: true
		 */
		readonly last_name: MigrationElementModels.TextElement

		/*
		 * Photo
		 *
		 * Codename: photo
		 * Id: eaec9ba3-9624-6875-04ec-80d0b2e00781
		 * Type: asset
		 * Required: false
		 */
		readonly photo: MigrationElementModels.AssetElement
	}
>
