import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.6.0' at 'Thu, 15 Sep 2022 09:52:52 GMT'
 *
 * Test
 * Id: 1499b802-b6ec-45d4-84d7-9e05ee379c06
 * Codename: test
 */
export type Test = IContentItem<{
  /**
   * fefe (asset)
   * Required: false
   * Id: 27e67a4c-fe1c-43d2-a9a2-192b0b5db68b
   * Codename: test__fefe
   */
  testFefe: Elements.AssetsElement;

  /**
   * fasfefase (text)
   * Required: false
   * Id: 44b1f309-5847-4fd3-b350-9fdcbf3c2008
   * Codename: test__fasfefase
   */
  testFasfefase: Elements.TextElement;
}>;
