
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-5'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing available item codenames
 *
 * Actor
 *
 * Codename: actor
 * Id: 58099989-319f-495f-aa36-cb3710854e36
 * Codename: actor
 */
export type ActorCodenames =
    | 'anne_hathaway'
    | 'bill_nighy'
    | 'billy_crystal'
    | 'christian_bale'
    | 'domhnall_gleeson'
    | 'jessica_chastain'
    | 'joel_edgerton'
    | 'kristen_wiig'
    | 'matt_damon'
    | 'nathalie_boltt'
    | 'rachel_mcadams'
    | 'sharlto_copley'
    | 'tom_hardy';
