
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-5'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

export const assetFolders = {
    /**
     * my folder A
     */
    my_folder_a: {
        name: 'my folder A',
        codename: 'my_folder_a',
        id: '6bb4814a-6a5c-4b8c-836e-7f83b008d5d1',
        externalId: undefined,
        folders: {
            /**
             * my folder nested A
             */
            my_folder_nested_a: {
                name: 'my folder nested A',
                codename: 'my_folder_nested_a',
                id: '555784e5-e92e-4a86-b40b-d642afbf7b4e',
                externalId: undefined,
                folders: {
                    /**
                     * even more nested A
                     */
                    even_more_nested_a: {
                        name: 'even more nested A',
                        codename: 'even_more_nested_a',
                        id: 'd26940cc-6c8d-41e6-93a0-0748c854b100',
                        externalId: undefined,
                        folders: {}
                    },

                    /**
                     * even more nested B
                     */
                    even_more_nested_b: {
                        name: 'even more nested B',
                        codename: 'even_more_nested_b',
                        id: '97fc4b03-98d2-44b4-8e03-b223a013b0b6',
                        externalId: undefined,
                        folders: {}
                    }
                }
            }
        }
    },

    /**
     * my folder B
     */
    my_folder_b: {
        name: 'my folder B',
        codename: 'my_folder_b',
        id: '58d1c135-42cb-43c2-a2cd-c615e0a36e83',
        externalId: undefined,
        folders: {}
    }
} as const;
