
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@7.4.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Migration Toolkit - tests
* Environment: Production
* Id: 5ddb8f47-a51f-0124-35b1-f6634fa91ae2
* 
* -------------------------------------------------------------------------------
**/

export const assetFolders = {
    /**
     * my-folder
     */
    myFolder: {
        codename: 'my_folder',
        id: 'f1c6ba01-3b13-41ce-81e7-3125840b0b0e',
        externalId: undefined,
        name: 'my-folder',
        folders: {}
    },

    /**
     * my-folder2
     */
    myFolder2: {
        codename: 'my_folder2',
        id: '44a00189-9298-4cf9-b8fb-3f208c3f4f8f',
        externalId: undefined,
        name: 'my-folder2',
        folders: {}
    }
} as const;
