
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

export const collections = {
    /**
     * Default
     */
    default: {
        name: 'Default',
        codename: 'default',
        id: '00000000-0000-0000-0000-000000000000'
    }
} as const;
