
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@7.4.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Migration Toolkit   tests
* Environment: Production
* Id: 5ddb8f47-a51f-0124-35b1-f6634fa91ae2
* 
* -------------------------------------------------------------------------------
**/

export const collections = {
    /**
     * Default
     */
    default: {
        codename: 'default',
        id: '00000000-0000-0000-0000-000000000000',
        name: 'Default'
    }
} as const;
