
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@7.4.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Migration Toolkit - tests
* Environment: Production
* Id: 5ddb8f47-a51f-0124-35b1-f6634fa91ae2
* 
* -------------------------------------------------------------------------------
**/

export const languages = {
    /**
     * Default project language
     */
    en: {
        codename: 'en',
        id: '00000000-0000-0000-0000-000000000000',
        name: 'Default project language',
        isActive: true,
        isDefault: true,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined
    },

    /**
     * Spanish
     */
    es: {
        codename: 'es',
        id: '71cf90e5-8124-43e3-8ef4-bbb8bdcd22ae',
        name: 'Spanish',
        isActive: true,
        isDefault: false,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined
    }
} as const;
