/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

export const spaces = {
	/*
	 * Movies
	 */
	movies: {
		name: 'Movies',
		codename: 'movies',
		id: 'ae7187c1-b38b-4356-8ebc-4f9f4d84496a'
	},

	/*
	 * Global
	 */
	global: {
		name: 'Global',
		codename: 'global',
		id: '2de65a86-d41c-4fea-ba0b-9cf61584a6d5'
	}
} as const;
