
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@7.4.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Migration Toolkit   tests
* Environment: Production
* Id: 5ddb8f47-a51f-0124-35b1-f6634fa91ae2
* 
* -------------------------------------------------------------------------------
**/

export const taxonomies = {
    /**
     * Category
     */
    category: {
        codename: 'category',
        externalId: undefined,
        id: 'c1b56389-f00a-4917-95c4-3b02ea3610ea',
        name: 'Category',
        terms: {
            /**
             * action
             */
            action: {
                codename: 'action',
                id: 'e3410312-52d6-4c15-8e23-e5a4cc57a204',
                externalId: undefined,
                name: 'action',
                terms: {}
            },

            /**
             * animation
             */
            animation: {
                codename: 'animation',
                id: '2d8a95a8-61c9-4add-94a1-1d7944098144',
                externalId: undefined,
                name: 'animation',
                terms: {}
            },

            /**
             * comedy
             */
            comedy: {
                codename: 'comedy',
                id: 'eddaa24b-fb5c-4a44-8507-8dd7a45fdc39',
                externalId: undefined,
                name: 'comedy',
                terms: {}
            },

            /**
             * drama
             */
            drama: {
                codename: 'drama',
                id: '7377ea7c-d928-408a-bfb8-a0bf7392c996',
                externalId: undefined,
                name: 'drama',
                terms: {}
            },

            /**
             * romance
             */
            romance: {
                codename: 'romance',
                id: 'fe8bdfdb-cc13-4890-ab45-a6669e94d1d0',
                externalId: undefined,
                name: 'romance',
                terms: {}
            },

            /**
             * sci_fi
             */
            sciFi: {
                codename: 'sci_fi',
                id: '1432c10c-096c-47c5-a045-dcd6dc4af366',
                externalId: undefined,
                name: 'sci_fi',
                terms: {}
            }
        }
    },

    /**
     * Release category
     */
    releaseCategory: {
        codename: 'release_category',
        externalId: undefined,
        id: '4dbfc78f-5ea2-4f33-880d-193c75e0b975',
        name: 'Release category',
        terms: {
            /**
             * global_release
             */
            globalRelease: {
                codename: 'global_release',
                id: 'afb51aba-cb5a-499a-973c-d5b44fdeafcf',
                externalId: undefined,
                name: 'global_release',
                terms: {}
            },

            /**
             * us_only
             */
            usOnly: {
                codename: 'us_only',
                id: '3f8bddaf-c203-471b-af76-6539d3e72e89',
                externalId: undefined,
                name: 'us_only',
                terms: {}
            }
        }
    }
} as const;
