
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@7.4.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Migration Toolkit - tests
* Environment: Production
* Id: 5ddb8f47-a51f-0124-35b1-f6634fa91ae2
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = 'en' | 'es';

/**
 * Type representing all content types
 */
export type ContentTypeCodenames = 'actor' | 'movie' | 'special_type' | 'test';

/**
 * Type representing all collections
 */
export type CollectionCodenames = 'default';

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = 'default' | 'my_test_workflow';

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames =
    | 'archived'
    | 'draft_3171da5'
    | 'draft'
    | 'published'
    | 'ready_for_review'
    | 'ready_to_publish'
    | 'scheduled';
