/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all codenames
 *
 * Type: Collection
 */
export const collectionCodenames = ['default'] as const;

/*
 * Type representing all codenames
 *
 * Type: Collection
 */
export type CollectionCodenames = (typeof collectionCodenames)[number];

/*
 * Typeguard for codename
 *
 * Type: Collection
 */
export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
	return typeof value === 'string' && (collectionCodenames as readonly string[]).includes(value);
}
