/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-2'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Object with all values of Collection codenames
 */
export const collectionCodenames = ['default'] as const;

/*
 * Type representing Collection codenames
 */
export type CollectionCodenames = (typeof collectionCodenames)[number];

/*
 * Type guard for Collection codenames
 */
export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
	return typeof value === 'string' && (collectionCodenames as readonly string[]).includes(value);
}
