
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object with all values of Collection codenames in Collection
 */
export const collectionCodenames = ['default'] as const;

/**
 * Type representing Collection codenames in Collection
 */
export type CollectionCodenames = (typeof collectionCodenames)[number];

/**
 * Type guard for Collection codenames in Collection
 */
export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
    return typeof value === 'string' && (collectionCodenames as readonly string[]).includes(value);
}
