
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object containing all Collection codenames
 */
export const collectionValues = ['default'] as const;

/**
 * Type representing Collection codenames
 */
export type CollectionCodenames = (typeof collectionValues)[number];

/**
 * Type guard for Collection codenames
 */
export function isCollection(value: string | undefined | null): value is CollectionCodenames {
    return typeof value === 'string' && (collectionValues as readonly string[]).includes(value);
}
