
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { CollectionCodenames } from './_collections.js';

/**
 * Type representing codename of Default Collection
 *
 * Codename: default
 */
export type DefaultCollectionCodename = Extract<CollectionCodenames, 'default'>;

/**
 * Type guard for Default entity
 *
 * Codename: default
 */
export function isDefaultCollectionCodename(value: string | undefined | null): value is DefaultCollectionCodename {
    return typeof value === 'string' && value === ('default' satisfies DefaultCollectionCodename);
}
