/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "./_collections.generated.js"

/*
 * Type representing codename of 'Default' collection
 */
export type DefaultCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">

/*
 * Typeguard for codename of 'Default' collection
 */
export function isDefaultCollectionCodename(value: string | undefined | null): value is DefaultCollectionCodename {
	return typeof value === "string" && value === ("default" satisfies DefaultCollectionCodename)
}
