/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-2'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Object with all values of ContentType codenames
 */
export const contentTypeCodenames = ['actor', 'movie'] as const;

/*
 * Type representing ContentType codenames
 */
export type ContentTypeCodenames = (typeof contentTypeCodenames)[number];

/*
 * Type guard for ContentType codenames
 */
export function isContentTypeCodename(value: string | undefined | null): value is ContentTypeCodenames {
	return typeof value === 'string' && (contentTypeCodenames as readonly string[]).includes(value);
}
