/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { ContentTypeCodenames } from './_contentTypes.js';

/*
 * Type representing codename of Actor
 *
 * Codename: actor
 */
export type ActorContentTypeCodename = Extract<ContentTypeCodenames, 'actor'>;

/*
 * Type guard for Actor
 *
 * Codename: actor
 */
export function isActorContentTypeCodename(value: string | undefined | null): value is ActorContentTypeCodename {
	return typeof value === 'string' && value === ('actor' satisfies ActorContentTypeCodename);
}
