
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ContentTypeCodenames } from './core.contentType.js';

/**
 * Type representing ContentType entities
 *
 * Codename: actor
 * Id: 58099989-319f-495f-aa36-cb3710854e36
 */
export type ActorContentType = Extract<ContentTypeCodenames, 'actor'>;

/**
 * Type guard for Actor entity
 *
 * Codename: actor
 * Id: 58099989-319f-495f-aa36-cb3710854e36
 */
export function isActorContentType(value: string | undefined | null): value is ActorContentType {
    return typeof value === 'string' && value === ('actor' satisfies ActorContentType);
}
