
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object containing all ContentType codenames
 */
export const contentTypeValues = ['actor', 'movie'] as const;

/**
 * Type representing ContentType codenames
 */
export type ContentTypeCodenames = (typeof contentTypeValues)[number];

/**
 * Type guard for ContentType codenames
 */
export function isContentType(value: string | undefined | null): value is ContentTypeCodenames {
    return typeof value === 'string' && (contentTypeValues as readonly string[]).includes(value);
}
