/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-2'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { ContentTypeCodenames } from './_contentTypes.js';

/*
 * Type representing codename of Movie
 *
 * Codename: movie
 */
export type MovieContentTypeCodename = Extract<ContentTypeCodenames, 'movie'>;

/*
 * Type guard for Movie
 *
 * Codename: movie
 */
export function isMovieContentTypeCodename(value: string | undefined | null): value is MovieContentTypeCodename {
	return typeof value === 'string' && value === ('movie' satisfies MovieContentTypeCodename);
}
