
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ContentTypeCodenames } from './core.contentType.js';

/**
 * Type representing ContentType entities
 *
 * Codename: movie
 * Id: b0c0f9c2-ffb6-4e62-bac9-34e14172dd8c
 */
export type MovieContentType = Extract<ContentTypeCodenames, 'movie'>;

/**
 * Type guard for Movie entity
 *
 * Codename: movie
 * Id: b0c0f9c2-ffb6-4e62-bac9-34e14172dd8c
 */
export function isMovieContentType(value: string | undefined | null): value is MovieContentType {
    return typeof value === 'string' && value === ('movie' satisfies MovieContentType);
}
