/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Object with all values of Taxonomy codenames
 */
export const taxonomyCodenames = ['movietype', 'releasecategory'] as const;

/*
 * Type representing Taxonomy codenames
 */
export type TaxonomyCodenames = (typeof taxonomyCodenames)[number];

/*
 * Type guard for Taxonomy codenames
 */
export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
	return typeof value === 'string' && (taxonomyCodenames as readonly string[]).includes(value);
}
