
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@7.4.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Migration Toolkit - tests
* Environment: Production
* Id: 5ddb8f47-a51f-0124-35b1-f6634fa91ae2
* 
* -------------------------------------------------------------------------------
**/

/**
 * Category
 *
 * Codename: category
 * Id: c1b56389-f00a-4917-95c4-3b02ea3610ea
 */
export type Category = 'action' | 'animation' | 'comedy' | 'drama' | 'romance' | 'sci_fi';
