
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object containing all Taxonomy codenames
 */
export const taxonomyValues = ['movietype', 'releasecategory'] as const;

/**
 * Type representing Taxonomy codenames
 */
export type TaxonomyCodenames = (typeof taxonomyValues)[number];

/**
 * Type guard for Taxonomy codenames
 */
export function isTaxonomy(value: string | undefined | null): value is TaxonomyCodenames {
    return typeof value === 'string' && (taxonomyValues as readonly string[]).includes(value);
}
