
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object with all values of Taxonomy codenames in Taxonomy
 */
export const taxonomyCodenames = ['movietype', 'releasecategory'] as const;

/**
 * Type representing Taxonomy codenames in Taxonomy
 */
export type TaxonomyCodenames = (typeof taxonomyCodenames)[number];

/**
 * Type guard for Taxonomy codenames in Taxonomy
 */
export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
    return typeof value === 'string' && (taxonomyCodenames as readonly string[]).includes(value);
}
