/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from './_taxonomies.js';

/*
 * Type representing codename of 'MovieType' taxonomy
 */
export type MovieTypeTaxonomyCodename = Extract<TaxonomyCodenames, 'movietype'>;

/*
 * Typeguard for codename of 'MovieType' taxonomy
 */
export function isMovieTypeTaxonomyCodename(value: string | undefined | null): value is MovieTypeTaxonomyCodename {
	return typeof value === 'string' && value === ('movietype' satisfies MovieTypeTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const movieTypeTermCodenames = ['student', 'tv', 'blockbuster', 'cinema_only', 'film'] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type MovieTypeTermCodenames = (typeof movieTypeTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isMovieTypeTermCodename(value: string | undefined | null): value is MovieTypeTermCodenames {
	return typeof value === 'string' && (movieTypeTermCodenames as readonly string[]).includes(value);
}
