
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { TaxonomyCodenames } from './core.taxonomy.js';

/**
 * Type representing Taxonomy entities
 *
 * Codename: movietype
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 */
export type MovieTypeTaxonomyCodename = Extract<TaxonomyCodenames, 'movietype'>;

/**
 * Type guard for MovieType entity
 *
 * Codename: movietype
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 */
export function isMovieTypeTaxonomyCodename(value: string | undefined | null): value is MovieTypeTaxonomyCodename {
    return typeof value === 'string' && value === ('movietype' satisfies MovieTypeTaxonomyCodename);
}

/**
 * Type representing taxonomy term codenames in MovieType taxonomy
 */
export const movieTypeTaxonomyTermCodenames = ['student', 'tv', 'blockbuster', 'cinema_only', 'film'] as const;

/**
 * Type representing MovieType taxonomy terms
 *
 * Codename: movietype
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 */
export type MovieTypeTaxonomyTermCodenames = (typeof movieTypeTaxonomyTermCodenames)[number];

/**
 * Type guard for MovieType taxonomy term codenames
 */
export function isMovieTypeTaxonomyTermCodename(value: string | undefined | null): value is MovieTypeTaxonomyTermCodenames {
    return typeof value === 'string' && (movieTypeTaxonomyTermCodenames as readonly string[]).includes(value);
}
