/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "./_taxonomies.generated.js"

/*
 * Type representing codename of 'Movie Type 2' taxonomy
 */
export type MovieType2TaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "my_taxonomy_with_spaces">

/*
 * Typeguard for codename of 'Movie Type 2' taxonomy
 */
export function isMovieType2TaxonomyCodename(value: string | undefined | null): value is MovieType2TaxonomyCodename {
	return typeof value === "string" && value === ("my_taxonomy_with_spaces" satisfies MovieType2TaxonomyCodename)
}

/*
 * Array of all taxonomy term codenames
 */
export const movieType2TaxonomyTermCodenames = [] as const

/*
 * Type representing all taxonomy term codenames
 */
export type MovieType2TaxonomyTermCodenames = (typeof movieType2TaxonomyTermCodenames)[number]

/*
 * Typeguard for taxonomy term codename
 */
export function isMovieType2TaxonomyTermCodename(value: string | undefined | null): value is MovieType2TaxonomyTermCodenames {
	return typeof value === "string" && (movieType2TaxonomyTermCodenames as readonly string[]).includes(value)
}
