/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.js"

/*
 * Type representing codename of 'Movie Type' taxonomy
 */
export type MovieTypeTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "movietype">

/*
 * Typeguard for codename of 'Movie Type' taxonomy
 */
export function isMovieTypeTaxonomyCodename(value: string | undefined | null): value is MovieTypeTaxonomyCodename {
	return typeof value === "string" && value === ("movietype" satisfies MovieTypeTaxonomyCodename)
}

/*
 * Array of all taxonomy term codenames
 */
export const movieTypeTaxonomyTermCodenames = ["student", "tv", "blockbuster", "cinema_only", "film"] as const

/*
 * Type representing all taxonomy term codenames
 */
export type MovieTypeTaxonomyTermCodenames = (typeof movieTypeTaxonomyTermCodenames)[number]

/*
 * Typeguard for taxonomy term codename
 */
export function isMovieTypeTaxonomyTermCodename(value: string | undefined | null): value is MovieTypeTaxonomyTermCodenames {
	return typeof value === "string" && (movieTypeTaxonomyTermCodenames as readonly string[]).includes(value)
}
