
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { TaxonomyCodenames } from './core.taxonomy.js';

/**
 * Type representing Taxonomy entities
 *
 * Codename: movietype
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 */
export type MovieTypeTaxonomy = Extract<TaxonomyCodenames, 'movietype'>;

/**
 * Type guard for MovieType entity
 *
 * Codename: movietype
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 */
export function isMovieTypeTaxonomy(value: string | undefined | null): value is MovieTypeTaxonomy {
    return typeof value === 'string' && value === ('movietype' satisfies MovieTypeTaxonomy);
}
