/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from './_taxonomies.js';

/*
 * Type representing codename of MovieType
 *
 * Codename: movietype
 */
export type MovieTypeTaxonomyCodename = Extract<TaxonomyCodenames, 'movietype'>;

/*
 * Type guard for MovieType
 *
 * Codename: movietype
 */
export function isMovieTypeTaxonomyCodename(value: string | undefined | null): value is MovieTypeTaxonomyCodename {
	return typeof value === 'string' && value === ('movietype' satisfies MovieTypeTaxonomyCodename);
}

/*
 * Object with all values of taxonomy term codenames in MovieType
 */
export const movieTypeTaxonomyTermCodenames = ['student', 'tv', 'blockbuster', 'cinema_only', 'film'] as const;

/*
 * Type representing taxonomy term codenames in MovieType
 */
export type MovieTypeTaxonomyTermCodenames = (typeof movieTypeTaxonomyTermCodenames)[number];

/*
 * Type guard for taxonomy term codenames in MovieType
 */
export function isMovieTypeTaxonomyTermCodename(value: string | undefined | null): value is MovieTypeTaxonomyTermCodenames {
	return typeof value === 'string' && (movieTypeTaxonomyTermCodenames as readonly string[]).includes(value);
}
