
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * MovieType
 *
 * Codename: movietype
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 */
export type Movietype = 'student' | 'tv' | 'blockbuster' | 'cinema_only' | 'film';
