/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-4'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from './_taxonomies.js';

/*
 * Type representing codename of 'MovieType' taxonomy
 */
export type MovietypeTaxonomyCodename = Extract<TaxonomyCodenames, 'movietype'>;

/*
 * Typeguard for codename of 'MovieType' taxonomy
 */
export function isMovietypeTaxonomyCodename(value: string | undefined | null): value is MovietypeTaxonomyCodename {
	return typeof value === 'string' && value === ('movietype' satisfies MovietypeTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const movietypeTaxonomyTermCodenames = ['student', 'tv', 'blockbuster', 'cinema_only', 'film'] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type MovietypeTaxonomyTermCodenames = (typeof movietypeTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isMovietypeTaxonomyTermCodename(value: string | undefined | null): value is MovietypeTaxonomyTermCodenames {
	return typeof value === 'string' && (movietypeTaxonomyTermCodenames as readonly string[]).includes(value);
}
