/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-4'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from './_taxonomies.js';

/*
 * Type representing codename of 'ReleaseCategory' taxonomy
 */
export type ReleasecategoryTaxonomyCodename = Extract<TaxonomyCodenames, 'releasecategory'>;

/*
 * Typeguard for codename of 'ReleaseCategory' taxonomy
 */
export function isReleasecategoryTaxonomyCodename(value: string | undefined | null): value is ReleasecategoryTaxonomyCodename {
	return typeof value === 'string' && value === ('releasecategory' satisfies ReleasecategoryTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const releasecategoryTaxonomyTermCodenames = ['global_release', 'us_only', 'local_release'] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type ReleasecategoryTaxonomyTermCodenames = (typeof releasecategoryTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isReleasecategoryTaxonomyTermCodename(value: string | undefined | null): value is ReleasecategoryTaxonomyTermCodenames {
	return typeof value === 'string' && (releasecategoryTaxonomyTermCodenames as readonly string[]).includes(value);
}
