/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.js"

/*
 * Type representing codename of 'Release Category' taxonomy
 */
export type ReleaseCategoryTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "releasecategory">

/*
 * Typeguard for codename of 'Release Category' taxonomy
 */
export function isReleaseCategoryTaxonomyCodename(value: string | undefined | null): value is ReleaseCategoryTaxonomyCodename {
	return typeof value === "string" && value === ("releasecategory" satisfies ReleaseCategoryTaxonomyCodename)
}

/*
 * Array of all taxonomy term codenames
 */
export const releaseCategoryTaxonomyTermCodenames = ["global_release", "us_only", "local_release"] as const

/*
 * Type representing all taxonomy term codenames
 */
export type ReleaseCategoryTaxonomyTermCodenames = (typeof releaseCategoryTaxonomyTermCodenames)[number]

/*
 * Typeguard for taxonomy term codename
 */
export function isReleaseCategoryTaxonomyTermCodename(value: string | undefined | null): value is ReleaseCategoryTaxonomyTermCodenames {
	return typeof value === "string" && (releaseCategoryTaxonomyTermCodenames as readonly string[]).includes(value)
}
