
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for ReleaseCategory
 *
 * Codename: releasecategory
 * Id: 09b6a348-0f86-7a68-4af3-7cab9a5c60b7
 */
export const ReleaseCategoryValues = ['global_release', 'us_only', 'local_release'] as const;

/**
 * Type representing ReleaseCategory taxonomy
 *
 * Codename: releasecategory
 * Id: 09b6a348-0f86-7a68-4af3-7cab9a5c60b7
 */
export type ReleaseCategory = (typeof ReleaseCategoryValues)[number];

/**
 * Type guard for ReleaseCategory
 *
 * Codename: releasecategory
 * Id: 09b6a348-0f86-7a68-4af3-7cab9a5c60b7
 */
export function isReleaseCategory(value: string | undefined | null): value is ReleaseCategory {
    return typeof value === 'string' && (ReleaseCategoryValues as readonly string[]).includes(value);
}
