/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

export * from './collections/index.js';
export * from './contentTypes/index.js';
export * from './elements/index.js';
export * from './languages/index.js';
export * from './system/index.js';
export * from './taxonomies/index.js';
export * from './workflows/index.js';
