/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

export * from "./codenames/actor.codenames.generated.js"
export * from "./codenames/movie.codenames.generated.js"
export * from "./items/actor.items.generated.js"
export * from "./items/movie.items.generated.js"
