
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

/**
 * Object with all values of Element codenames
 */
export const elementCodenames = [
    'url',
    'first_name',
    'last_name',
    'photo',
    'title',
    'plot',
    'released',
    'length',
    'poster',
    'category',
    'stars',
    'seoname',
    'releasecategory'
] as const;

/**
 * Type representing Element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number];

/**
 * Type guard for Element codenames
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
    return typeof value === 'string' && (elementCodenames as readonly string[]).includes(value);
}
