/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
	"url",
	"first_name",
	"last_name",
	"photo",
	"title",
	"plot",
	"released",
	"length",
	"poster",
	"category",
	"stars",
	"seoname",
	"releasecategory"
] as const

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number]

/*
 * Typeguard for element codename
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
	return typeof value === "string" && (elementCodenames as readonly string[]).includes(value)
}
