
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of Category Element
 *
 * Codename: category
 */
export type CategoryElementCodename = Extract<ElementCodenames, 'category'>;

/**
 * Type guard for Category entity
 *
 * Codename: category
 */
export function isCategoryElementCodename(value: string | undefined | null): value is CategoryElementCodename {
    return typeof value === 'string' && value === ('category' satisfies CategoryElementCodename);
}
