
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of First name Element
 *
 * Codename: first_name
 */
export type FirstNameElementCodename = Extract<ElementCodenames, 'first_name'>;

/**
 * Type guard for First name entity
 *
 * Codename: first_name
 */
export function isFirstNameElementCodename(value: string | undefined | null): value is FirstNameElementCodename {
    return typeof value === 'string' && value === ('first_name' satisfies FirstNameElementCodename);
}
