/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { ElementCodenames } from './_elements.js';

/*
 * Type representing codename of Last name
 *
 * Codename: last_name
 */
export type LastNameElementCodename = Extract<ElementCodenames, 'last_name'>;

/*
 * Type guard for Last name entity
 *
 * Codename: last_name
 */
export function isLastNameElementCodename(value: string | undefined | null): value is LastNameElementCodename {
	return typeof value === 'string' && value === ('last_name' satisfies LastNameElementCodename);
}
