
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of Length Element
 *
 * Codename: length
 */
export type LengthElementCodename = Extract<ElementCodenames, 'length'>;

/**
 * Type guard for Length entity
 *
 * Codename: length
 */
export function isLengthElementCodename(value: string | undefined | null): value is LengthElementCodename {
    return typeof value === 'string' && value === ('length' satisfies LengthElementCodename);
}
