
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of Photo Element
 *
 * Codename: photo
 */
export type PhotoElementCodename = Extract<ElementCodenames, 'photo'>;

/**
 * Type guard for Photo entity
 *
 * Codename: photo
 */
export function isPhotoElementCodename(value: string | undefined | null): value is PhotoElementCodename {
    return typeof value === 'string' && value === ('photo' satisfies PhotoElementCodename);
}
