
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of Plot Element
 *
 * Codename: plot
 */
export type PlotElementCodename = Extract<ElementCodenames, 'plot'>;

/**
 * Type guard for Plot entity
 *
 * Codename: plot
 */
export function isPlotElementCodename(value: string | undefined | null): value is PlotElementCodename {
    return typeof value === 'string' && value === ('plot' satisfies PlotElementCodename);
}
