/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { ElementCodenames } from './_elements.js';

/*
 * Type representing codename of Poster
 *
 * Codename: poster
 */
export type PosterElementCodename = Extract<ElementCodenames, 'poster'>;

/*
 * Type guard for Poster entity
 *
 * Codename: poster
 */
export function isPosterElementCodename(value: string | undefined | null): value is PosterElementCodename {
	return typeof value === 'string' && value === ('poster' satisfies PosterElementCodename);
}
