
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of Released Element
 *
 * Codename: released
 */
export type ReleasedElementCodename = Extract<ElementCodenames, 'released'>;

/**
 * Type guard for Released entity
 *
 * Codename: released
 */
export function isReleasedElementCodename(value: string | undefined | null): value is ReleasedElementCodename {
    return typeof value === 'string' && value === ('released' satisfies ReleasedElementCodename);
}
