/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { ElementCodenames } from './_elements.js';

/*
 * Type representing codename of ReleaseCategory
 *
 * Codename: releasecategory
 */
export type ReleaseCategoryElementCodename = Extract<ElementCodenames, 'releasecategory'>;

/*
 * Type guard for ReleaseCategory entity
 *
 * Codename: releasecategory
 */
export function isReleaseCategoryElementCodename(value: string | undefined | null): value is ReleaseCategoryElementCodename {
	return typeof value === 'string' && value === ('releasecategory' satisfies ReleaseCategoryElementCodename);
}
