
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of SeoName Element
 *
 * Codename: seoname
 */
export type SeoNameElementCodename = Extract<ElementCodenames, 'seoname'>;

/**
 * Type guard for SeoName entity
 *
 * Codename: seoname
 */
export function isSeoNameElementCodename(value: string | undefined | null): value is SeoNameElementCodename {
    return typeof value === 'string' && value === ('seoname' satisfies SeoNameElementCodename);
}
