
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of Stars Element
 *
 * Codename: stars
 */
export type StarsElementCodename = Extract<ElementCodenames, 'stars'>;

/**
 * Type guard for Stars entity
 *
 * Codename: stars
 */
export function isStarsElementCodename(value: string | undefined | null): value is StarsElementCodename {
    return typeof value === 'string' && value === ('stars' satisfies StarsElementCodename);
}
