
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { ElementCodenames } from './_elements.js';

/**
 * Type representing codename of Title Element
 *
 * Codename: title
 */
export type TitleElementCodename = Extract<ElementCodenames, 'title'>;

/**
 * Type guard for Title entity
 *
 * Codename: title
 */
export function isTitleElementCodename(value: string | undefined | null): value is TitleElementCodename {
    return typeof value === 'string' && value === ('title' satisfies TitleElementCodename);
}
