/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { ElementCodenames } from './_elements.js';

/*
 * Type representing codename of Url
 *
 * Codename: url
 */
export type UrlElementCodename = Extract<ElementCodenames, 'url'>;

/*
 * Type guard for Url entity
 *
 * Codename: url
 */
export function isUrlElementCodename(value: string | undefined | null): value is UrlElementCodename {
	return typeof value === 'string' && value === ('url' satisfies UrlElementCodename);
}
