/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */

/**
 * Person
 */

export const person = {
    codename: 'person',
    id: '081a7b99-575d-473c-9cd0-67094803da73',
    externalId: undefined,
    name: 'Person',
    elements: {
        /**
         * Bio (rich_text)
         */
        bio: {
            codename: 'bio',
            id: '8e24b232-dfdd-4f4c-8e62-379baf194c24',
            externalId: undefined,
            name: 'Bio',
            required: false,
            type: 'rich_text'
        },

        /**
         * Category (taxonomy)
         */
        category: {
            codename: 'category',
            id: '81ff1d64-f4f8-4cf4-bc1e-a076b554cd3d',
            externalId: undefined,
            name: 'Category',
            required: false,
            type: 'taxonomy'
        },

        /**
         * custom element (custom)
         */
        custom_element: {
            codename: 'custom_element',
            id: '85fa4bd3-0445-466e-bb6f-8c3228ea12a6',
            externalId: undefined,
            name: 'custom element',
            required: false,
            type: 'custom'
        },

        /**
         * Date of Birth (date_time)
         */
        date_of_birth: {
            codename: 'date_of_birth',
            id: 'fd009675-1d52-4259-a72a-4c52808fbebd',
            externalId: undefined,
            name: 'Date of Birth',
            required: false,
            type: 'date_time'
        },

        /**
         * Favorite Number (number)
         */
        favorite_number: {
            codename: 'favorite_number',
            id: 'db98d495-49b5-4ab5-b08c-ef31fae3277d',
            externalId: undefined,
            name: 'Favorite Number',
            required: false,
            type: 'number'
        },

        /**
         * Friends (modular_content)
         */
        friends: {
            codename: 'friends',
            id: '7ccfe5f8-373f-440b-b622-4ba7867ec248',
            externalId: undefined,
            name: 'Friends',
            required: false,
            type: 'modular_content'
        },

        /**
         * Gender (multiple_choice)
         */
        gender: {
            codename: 'gender',
            id: 'da20aeac-83d4-4da2-b6f1-ab3395dcc922',
            externalId: undefined,
            name: 'Gender',
            required: false,
            type: 'multiple_choice',
            options: {
                man: {
                    name: 'Man',
                    id: '6dd50d21-cd89-4717-960b-393594104614',
                    codename: 'man',
                    externalId: undefined
                },
                woman: {
                    name: 'Woman',
                    id: 'e7656e14-5370-41df-ace6-8479f2acd68a',
                    codename: 'woman',
                    externalId: undefined
                },
                other: {
                    name: 'Other',
                    id: 'c20581dd-13ea-408e-bd3b-76a1b4fae51a',
                    codename: 'other',
                    externalId: undefined
                }
            }
        },

        /**
         * Name and Surname (text)
         */
        name_and_surname: {
            codename: 'name_and_surname',
            id: 'd0726df3-7ca6-4183-bdc1-41c0fe573932',
            externalId: undefined,
            name: 'Name and Surname',
            required: true,
            type: 'text'
        },

        /**
         * Profile Photo (asset)
         */
        profile_photo: {
            codename: 'profile_photo',
            id: '23ae3be4-aa8c-4bf3-8a30-4bb4d7a6fa71',
            externalId: undefined,
            name: 'Profile Photo',
            required: false,
            type: 'asset'
        },

        /**
         * URL slug (url_slug)
         */
        url_slug: {
            codename: 'url_slug',
            id: 'ea17615b-e0dc-4fba-8224-b8891ce8497c',
            externalId: undefined,
            name: 'URL slug',
            required: false,
            type: 'url_slug'
        }
    }
};
