/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */

/**
 * Repository
 */

export const repository = {
    codename: 'repository',
    id: 'c88be77c-83a6-4839-855f-66c28f624d1d',
    externalId: undefined,
    name: 'Repository',
    elements: {
        /**
         * Description (custom)
         */
        description: {
            codename: 'description',
            id: '2ba28366-7c0c-4b20-893e-90920e903798',
            externalId: undefined,
            name: 'Description',
            required: false,
            type: 'custom'
        },

        /**
         * Name (text)
         */
        name: {
            codename: 'name',
            id: 'ae29bcd9-a8dd-49c4-8a31-1becf790b4e9',
            externalId: undefined,
            name: 'Name',
            required: false,
            type: 'text'
        },

        /**
         * URL (text)
         */
        url: {
            codename: 'url',
            id: 'ff86d6ab-5528-4737-8389-35b83f97f880',
            externalId: undefined,
            name: 'URL',
            required: false,
            type: 'text'
        }
    }
};
