/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */

/**
 * Session
 */

export const session = {
    codename: 'session',
    id: '9dfcd879-0d06-45ca-9b2c-67fd9c6e3b34',
    externalId: undefined,
    name: 'Session',
    elements: {
        /**
         * Agenda (modular_content)
         */
        agenda: {
            codename: 'agenda',
            id: 'c6fa7f46-cf83-446d-8e36-830e423292e7',
            externalId: undefined,
            name: 'Agenda',
            required: false,
            type: 'modular_content'
        },

        /**
         * Assets (asset)
         */
        assets: {
            codename: 'assets',
            id: 'b73d60dc-2dd0-4a5e-9cd2-7ebe705dd1f2',
            externalId: undefined,
            name: 'Assets',
            required: false,
            type: 'asset'
        },

        /**
         * Checklist (multiple_choice)
         */
        checklist: {
            codename: 'checklist',
            id: 'c8fa819e-4640-442a-8248-293993b54ee0',
            externalId: undefined,
            name: 'Checklist',
            required: false,
            type: 'multiple_choice',
            options: {
                training_sessions_scheduled: {
                    name: 'Training sessions scheduled',
                    id: '7b58b382-9441-4daf-a2d4-8657b1537fcf',
                    codename: 'training_sessions_scheduled',
                    externalId: undefined
                },
                training_rooms_reserved: {
                    name: 'Training rooms reserved',
                    id: 'ec6e4746-2090-4ab0-8c4a-0644a1001924',
                    codename: 'training_rooms_reserved',
                    externalId: undefined
                },
                presentations_and_files_proofread: {
                    name: 'Presentations and files proofread',
                    id: '40793cb7-cc27-4e6c-a009-9fc98d685ce3',
                    codename: 'presentations_and_files_proofread',
                    externalId: undefined
                },
                introduction_and_supporting_files_uploaded: {
                    name: 'Introduction and supporting files uploaded',
                    id: 'ccc302d8-f52a-4921-b2dd-565d1bdefb7f',
                    codename: 'introduction_and_supporting_files_uploaded',
                    externalId: undefined
                },
                start_code_files_and_final_code_files_uploaded: {
                    name: 'START code files and FINAL code files uploaded',
                    id: '538b9f32-042b-420c-9315-7805fc723383',
                    codename: 'start_code_files_and_final_code_files_uploaded',
                    externalId: undefined
                },
                exercise_step_by_step_instructions_added: {
                    name: 'Exercise step by step instructions added',
                    id: '3b68b39b-e1c9-44bb-9dc1-045ed5b081ff',
                    codename: 'exercise_step_by_step_instructions_added',
                    externalId: undefined
                },
                training_session_tagged_in_confluence: {
                    name: 'Training session tagged in Confluence',
                    id: 'f7123fc0-7da9-4adc-bb02-02452d4d8ffe',
                    codename: 'training_session_tagged_in_confluence',
                    externalId: undefined
                }
            }
        },

        /**
         * Excercise (rich_text)
         */
        excercise: {
            codename: 'excercise',
            id: 'b852e079-fd6d-4cfa-b920-7eadb1bffc95',
            externalId: undefined,
            name: 'Excercise',
            required: false,
            type: 'rich_text'
        },

        /**
         * Name (text)
         */
        name: {
            codename: 'name',
            id: 'b26de2bb-e9f9-4dfe-a42a-f40f6252cf03',
            externalId: undefined,
            name: 'Name',
            required: false,
            type: 'text'
        },

        /**
         * Presenter (modular_content)
         */
        presenter: {
            codename: 'presenter',
            id: 'd34b6f20-8bb7-49a3-b0d4-6404cafa7bf1',
            externalId: undefined,
            name: 'Presenter',
            required: false,
            type: 'modular_content'
        },

        /**
         * Summary (rich_text)
         */
        summary: {
            codename: 'summary',
            id: '7e506a63-b5d9-4dd6-bb5f-bee9416601bc',
            externalId: undefined,
            name: 'Summary',
            required: false,
            type: 'rich_text'
        }
    }
};
