/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */

/**
 * Step
 */

export const step = {
    codename: 'step',
    id: 'c4b8e601-77f5-4535-b522-8b38db55873e',
    externalId: undefined,
    name: 'Step',
    elements: {
        /**
         * Text (rich_text)
         */
        text: {
            codename: 'text',
            id: '360eec57-77c0-4352-90be-fc86ecb1946a',
            externalId: undefined,
            name: 'Text',
            required: false,
            type: 'rich_text'
        }
    }
};
