/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */

/**
 * Training
 */

export const training = {
    codename: 'training',
    id: 'd4cf750f-61d3-4782-bf9c-b7184b7b2fc3',
    externalId: undefined,
    name: 'Training',
    elements: {
        /**
         * Author (modular_content)
         */
        author: {
            codename: 'author',
            id: '28082ed5-347f-4596-965c-5b05c4d4a50b',
            externalId: undefined,
            name: 'Author',
            required: false,
            type: 'modular_content'
        },

        /**
         * Description (rich_text)
         */
        description: {
            codename: 'description',
            id: 'ee37d129-673f-459c-a94d-807e24de61f5',
            externalId: undefined,
            name: 'Description',
            required: false,
            type: 'rich_text'
        },

        /**
         * Name (text)
         */
        name: {
            codename: 'name',
            id: '93f00d8b-ce52-4d26-96ae-4607a0438000',
            externalId: undefined,
            name: 'Name',
            required: false,
            type: 'text'
        },

        /**
         * Sessions (modular_content)
         */
        sessions: {
            codename: 'sessions',
            id: 'b6e2b3f7-3d0a-4b8a-bbd5-2b1e256528cd',
            externalId: undefined,
            name: 'Sessions',
            required: false,
            type: 'modular_content'
        }
    }
};
