/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */

/**
 * Website
 */

export const website = {
    codename: 'website',
    id: 'aeabe925-9221-4fb2-bc3a-2a91abc904fd',
    externalId: undefined,
    name: 'Website',
    elements: {
        /**
         * Description (rich_text)
         */
        description: {
            codename: 'description',
            id: '7ebea693-c2e5-4455-9242-e71832f24c87',
            externalId: undefined,
            name: 'Description',
            required: false,
            type: 'rich_text'
        },

        /**
         * Name (text)
         */
        name: {
            codename: 'name',
            id: '7b9e7b9f-d6ba-4838-830b-d7fbb864ab4e',
            externalId: undefined,
            name: 'Name',
            required: false,
            type: 'text'
        },

        /**
         * URL (text)
         */
        url: {
            codename: 'url',
            id: '15b01ff6-b05f-4a7f-8795-9ea6f9b7b997',
            externalId: undefined,
            name: 'URL',
            required: false,
            type: 'text'
        }
    }
};
