/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Project name: Movie Database
 * Environment: Production
 * Environment Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 */
export const assetFolders = {
    /**
     * my folder A
     */
    myFolderA: {
        id: '6bb4814a-6a5c-4b8c-836e-7f83b008d5d1',
        name: 'my folder A',
        externalId: undefined,
        folders: {
            /**
             * my folder nested A
             */
            myFolderNestedA: {
                id: '555784e5-e92e-4a86-b40b-d642afbf7b4e',
                name: 'my folder nested A',
                externalId: undefined,
                folders: {
                    /**
                     * even more nested A
                     */
                    evenMoreNestedA: {
                        id: 'd26940cc-6c8d-41e6-93a0-0748c854b100',
                        name: 'even more nested A',
                        externalId: undefined,
                        folders: {}
                    },

                    /**
                     * even more nested B
                     */
                    evenMoreNestedB: {
                        id: '97fc4b03-98d2-44b4-8e03-b223a013b0b6',
                        name: 'even more nested B',
                        externalId: undefined,
                        folders: {}
                    }
                }
            }
        }
    },

    /**
     * my folder B
     */
    myFolderB: {
        id: '58d1c135-42cb-43c2-a2cd-c615e0a36e83',
        name: 'my folder B',
        externalId: undefined,
        folders: {}
    }
} as const;
