/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all codenames
 *
 * Type: Workflow
 */
export const workflowCodenames = ['default'] as const;

/*
 * Type representing all codenames
 *
 * Type: Workflow
 */
export type WorkflowCodenames = (typeof workflowCodenames)[number];

/*
 * Typeguard for codename
 *
 * Type: Workflow
 */
export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
	return typeof value === 'string' && (workflowCodenames as readonly string[]).includes(value);
}

/*
 * Array of all codenames
 *
 * Type: Workflow
 */
export const workflowStepCodenames = ['draft', 'review', 'ready_to_publish', 'published', 'archived', 'scheduled'] as const;

/*
 * Type representing all codenames
 *
 * Type: Workflow
 */
export type WorkflowStepCodenames = (typeof workflowStepCodenames)[number];

/*
 * Typeguard for codename
 *
 * Type: Workflow
 */
export function isWorkflowStepCodename(value: string | undefined | null): value is WorkflowStepCodenames {
	return typeof value === 'string' && (workflowStepCodenames as readonly string[]).includes(value);
}
