/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "./_workflows.js"

/*
 * Type representing codename of 'Default' workflow
 */
export type DefaultWorkflowCodename = Extract<WorkflowCodenames, "default">

/*
 * Typeguard for codename of 'Default' workflow
 */
export function isDefaultWorkflowCodename(value: string | undefined | null): value is DefaultWorkflowCodename {
	return typeof value === "string" && value === ("default" satisfies DefaultWorkflowCodename)
}

/*
 * Array of all workflow step codenames
 */
export const defaultWorkflowStepCodenames = ["draft", "review", "ready_to_publish", "published", "archived", "scheduled"] as const

/*
 * Type representing all workflow step codenames
 */
export type DefaultWorkflowStepCodenames = (typeof defaultWorkflowStepCodenames)[number]

/*
 * Typeguard for workflow step codename
 */
export function isDefaultWorkflowStepCodename(value: string | undefined | null): value is DefaultWorkflowStepCodenames {
	return typeof value === "string" && (defaultWorkflowStepCodenames as readonly string[]).includes(value)
}
