
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Movie Database
* Environment: Production
* Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
* 
* -------------------------------------------------------------------------------
**/

import type { WorkflowCodenames } from './core.workflow.js';

/**
 * Type representing Workflow entities
 *
 * Codename: default
 * Id: 00000000-0000-0000-0000-000000000000
 */
export type DefaultWorkflow = Extract<WorkflowCodenames, 'default'>;

/**
 * Type guard for Default entity
 *
 * Codename: default
 * Id: 00000000-0000-0000-0000-000000000000
 */
export function isDefaultWorkflow(value: string | undefined | null): value is DefaultWorkflow {
    return typeof value === 'string' && value === ('default' satisfies DefaultWorkflow);
}

/**
 * Type representing workflow step codenames in Default workflow
 */
export type DefaultWorkflowStepCodenames = 'draft' | 'ready_to_publish' | 'review';
