import {
    pascalCasePropertyNameResolver} from '@kentico/kontent-delivery';
import { name, version } from '../package.json';

export class CommonHelper {
    getAutogenerateNote(addTimestamp: boolean): string {
        if (addTimestamp) {
            return `Generated by '${name}@${version}' at '${new Date().toUTCString()}'`;
        }

        return `Generated by '${name}@${version}'`;
    }

    toPascalCase(text: string): string {
        // use element resolver from SDK as it provides required functionality
        return pascalCasePropertyNameResolver('', text);
    }

    escapeNameValue(value: string): string {
       return value.replace('\'', '\\\'');
    }
}

export const commonHelper = new CommonHelper();
