/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Mon, 28 Mar 2022 14:36:32 GMT'
 *
 * Movie Database
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * Environment: Production
 */
export const projectModel = {
  languages: {
    /**
     * English
     * Id: 00000000-0000-0000-0000-000000000000
     * Codename: en
     * Is Active: true
     * Is Default: true
     * Fallback language Id: 00000000-0000-0000-0000-000000000000
     */
    en: {
      codename: 'en',
      name: 'English',
    },

    /**
     * cz
     * Id: 41ccb26f-ceab-04d0-6ffa-9c7c5358aa8f
     * Codename: cz
     * Is Active: true
     * Is Default: false
     * Fallback language Id: 00000000-0000-0000-0000-000000000000
     */
    cz: {
      codename: 'cz',
      name: 'cz',
    },

    /**
     * German
     * Id: 14f7bcc0-4fd6-4b77-8c22-70e5ccfdae1d
     * Codename: German
     * Is Active: false
     * Is Default: false
     * Fallback language Id: 00000000-0000-0000-0000-000000000000
     */
    German: {
      codename: 'German',
      name: 'German',
    },
  },
  contentTypes: {
    /**
     * Movie
     * Id: b0c0f9c2-ffb6-4e62-bac9-34e14172dd8c
     * Codename: movie
     */
    movie: {
      codename: 'movie',
      name: 'Movie',
      elements: {
        /**
         * Title (text)
         * Required: true
         * Id: 3473187e-dc78-eff2-7099-f690f7042d4a
         * Codename: title
         */
        title: {
          codename: 'title',
          name: 'Title',
        },

        /**
         * Plot (rich_text)
         * Required: false
         * Id: f7ee4f27-27fd-a19b-3c5c-102aae1c50ce
         * Codename: plot
         */
        plot: {
          codename: 'plot',
          name: 'Plot',
        },

        /**
         * Released (date_time)
         * Required: false
         * Id: 5ccf4644-0d65-5d96-9a32-f4ea21974d51
         * Codename: released
         */
        released: {
          codename: 'released',
          name: 'Released',
        },

        /**
         * Length (number)
         * Required: false
         * Id: 7e8ecfab-a419-27ee-d8ec-8adb76fd007c
         * Codename: length
         */
        length: {
          codename: 'length',
          name: 'Length',
        },

        /**
         * Poster (asset)
         * Required: false
         * Id: a39a7237-9503-a1ae-8431-5b6cdb85ae9d
         * Codename: poster
         */
        poster: {
          codename: 'poster',
          name: 'Poster',
        },

        /**
         * Category (multiple_choice)
         * Required: false
         * Id: 9821c252-6414-f549-c17f-cc171dd87713
         * Codename: category
         */
        category: {
          codename: 'category',
          name: 'Category',
        },

        /**
         * Stars (modular_content)
         * Required: false
         * Id: aa26a55d-19f8-7501-fea3-b0d9b1eeac71
         * Codename: stars
         */
        stars: {
          codename: 'stars',
          name: 'Stars',
        },

        /**
         * SeoName (url_slug)
         * Required: false
         * Id: 756cc91a-a090-60f9-a7f0-f505bfbe046c
         * Codename: seoname
         */
        seoname: {
          codename: 'seoname',
          name: 'SeoName',
        },
      },
    },

    /**
     * Actor
     * Id: 58099989-319f-495f-aa36-cb3710854e36
     * Codename: actor
     */
    actor: {
      codename: 'actor',
      name: 'Actor',
      elements: {
        /**
         * Url (url_slug)
         * Required: false
         * Id: c8658782-f209-a573-9c85-430fb4e3e9f0
         * Codename: url
         */
        url: {
          codename: 'url',
          name: 'Url',
        },

        /**
         * First name (text)
         * Required: true
         * Id: 14dd70e5-c42d-f111-9640-c82b443edf1d
         * Codename: first_name
         *
         * This is the first name of the actor
         */
        first_name: {
          codename: 'first_name',
          name: 'First name',
        },

        /**
         * Last name (text)
         * Required: true
         * Id: 9f7a0dd4-af3a-95ca-0358-400c14ce7075
         * Codename: last_name
         */
        last_name: {
          codename: 'last_name',
          name: 'Last name',
        },

        /**
         * Photo (asset)
         * Required: false
         * Id: eaec9ba3-9624-6875-04ec-80d0b2e00781
         * Codename: photo
         */
        photo: {
          codename: 'photo',
          name: 'Photo',
        },
      },
    },
  },
  taxonomies: {
    /**
     * MovieType
     * Id: 365a17e6-1929-27ab-9f67-a9273c846717
     * Codename: movietype
     */
    movietype: {
      codename: 'movietype',
      name: 'MovieType',
      terms: {
        student: {
          codename: 'student',
          name: 'Student',
          terms: {},
        },
        film: {
          codename: 'film',
          name: 'Film',
          terms: {
            tv: {
              codename: 'tv',
              name: 'TV',
              terms: {},
            },
            blockbuster: {
              codename: 'blockbuster',
              name: 'Blockbuster',
              terms: {},
            },
            cinema_only: {
              codename: 'cinema_only',
              name: 'Cinema only',
              terms: {},
            },
          },
        },
      },
    },

    /**
     * ReleaseCategory
     * Id: 09b6a348-0f86-7a68-4af3-7cab9a5c60b7
     * Codename: releasecategory
     */
    releasecategory: {
      codename: 'releasecategory',
      name: 'ReleaseCategory',
      terms: {
        global_release: {
          codename: 'global_release',
          name: 'Global release',
          terms: {},
        },
        us_only: {
          codename: 'us_only',
          name: 'US only',
          terms: {},
        },
        local_release: {
          codename: 'local_release',
          name: 'Local release',
          terms: {},
        },
      },
    },
  },
};
