/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Wed, 23 Mar 2022 14:29:22 GMT'
 */
export const projectModel = {
  languages: {
    en: {
      codename: 'en',
      name: 'English',
    },
    cz: {
      codename: 'cz',
      name: 'cz',
    },
    German: {
      codename: 'German',
      name: 'German',
    },
  },
  contentTypes: {
    movie: {
      codename: 'movie',
      name: 'Movie',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        plot: {
          codename: 'plot',
          name: 'Plot',
        },
        released: {
          codename: 'released',
          name: 'Released',
        },
        length: {
          codename: 'length',
          name: 'Length',
        },
        poster: {
          codename: 'poster',
          name: 'Poster',
        },
        category: {
          codename: 'category',
          name: 'Category',
        },
        stars: {
          codename: 'stars',
          name: 'Stars',
        },
        seoname: {
          codename: 'seoname',
          name: 'SeoName',
        },
      },
    },
    actor: {
      codename: 'actor',
      name: 'Actor',
      elements: {
        url: {
          codename: 'url',
          name: 'Url',
        },
        first_name: {
          codename: 'first_name',
          name: 'First name',
        },
        last_name: {
          codename: 'last_name',
          name: 'Last name',
        },
        photo: {
          codename: 'photo',
          name: 'Photo',
        },
      },
    },
  },
  taxonomies: {
    movietype: {
      codename: 'movietype',
      name: 'MovieType',
      terms: {
        student: {
          codename: 'student',
          name: 'Student',
          terms: {},
        },
        film: {
          codename: 'film',
          name: 'Film',
          terms: {
            tv: {
              codename: 'tv',
              name: 'TV',
              terms: {},
            },
            blockbuster: {
              codename: 'blockbuster',
              name: 'Blockbuster',
              terms: {},
            },
            cinema_only: {
              codename: 'cinema_only',
              name: 'Cinema only',
              terms: {},
            },
          },
        },
      },
    },
    releasecategory: {
      codename: 'releasecategory',
      name: 'ReleaseCategory',
      terms: {
        global_release: {
          codename: 'global_release',
          name: 'Global release',
          terms: {},
        },
        us_only: {
          codename: 'us_only',
          name: 'US only',
          terms: {},
        },
        local_release: {
          codename: 'local_release',
          name: 'Local release',
          terms: {},
        },
      },
    },
  },
};
