import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Wed, 23 Mar 2022 13:35:46 GMT'
 */
export type actor = IContentItem<{
  url: Elements.UrlSlugElement;
  firstName: Elements.TextElement;
  lastName: Elements.TextElement;
  photo: Elements.AssetsElement;
}>;
