import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Mon, 28 Mar 2022 07:07:11 GMT'
 */
export type Actor = IContentItem<{
  url: Elements.UrlSlugElement;
  firstName: Elements.TextElement;
  lastName: Elements.TextElement;
  photo: Elements.AssetsElement;
}>;
