import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Wed, 23 Mar 2022 14:29:22 GMT'
 */
export type Movie = IContentItem<{
  title: Elements.TextElement;
  plot: Elements.RichTextElement;
  released: Elements.DateTimeElement;
  length: Elements.NumberElement;
  poster: Elements.AssetsElement;
  category: Elements.MultipleChoiceElement;
  stars: Elements.LinkedItemsElement<IContentItem>;
  seoname: Elements.UrlSlugElement;
  releasecategory: Elements.TaxonomyElement;
}>;
