import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Wed, 23 Mar 2022 13:53:23 GMT'
 */
export type movie = IContentItem<{
  title: Elements.TextElement;
  released: Elements.DateTimeElement;
  releasecategory: Elements.TaxonomyElement;
  seoname: Elements.UrlSlugElement;
  length: Elements.NumberElement;
  category: Elements.MultipleChoiceElement;
  poster: Elements.AssetsElement;
  stars: Elements.LinkedItemsElement<IContentItem>;
  plot: Elements.RichTextElement;
}>;
