/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Category
 * Id: f9cfab9c-3a44-462d-8d6e-4679c72c4aae
 * Codename: category
 */
export type Category = 'first' | 'second' | 'sub_first' | 'sub_second' | 'sub_sub_first' | 'y';
