/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Tue, 29 Mar 2022 07:19:43 GMT'
 *
 * MovieType
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 * Codename: movietype
 */
export type MovieType =
  | 'student'
  | 'film'
  | 'tv'
  | 'blockbuster'
  | 'cinema_only';
