/**
 * Generated by '@kontent-ai/model-generator@5.2.0' at 'Thu, 28 Jul 2022 10:05:53 GMT'
 *
 * MovieType
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 * Codename: movietype
 */
export type MovieType =
  | 'student'
  | 'film'
  | 'tv'
  | 'blockbuster'
  | 'cinema_only';
