/**
 * Generated by '@kontent-ai/model-generator@5.7.0' at 'Thu, 06 Oct 2022 09:00:53 GMT'
 *
 * MovieType
 * Id: 365a17e6-1929-27ab-9f67-a9273c846717
 * Codename: movietype
 */
export type MovieType =
  | 'blockbuster'
  | 'cinema_only'
  | 'film'
  | 'student'
  | 'tv';
