/**
 * Generated by '@kontent-ai/model-generator@5.2.0' at 'Thu, 28 Jul 2022 10:11:32 GMT'
 *
 * ReleaseCategory
 * Id: 09b6a348-0f86-7a68-4af3-7cab9a5c60b7
 * Codename: releasecategory
 */
export type ReleaseCategory = 'global_release' | 'us_only' | 'local_release';
