/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Tue, 19 Apr 2022 10:41:37 GMT'
 *
 * ReleaseCategory
 * Id: 09b6a348-0f86-7a68-4af3-7cab9a5c60b7
 * Codename: releasecategory
 */
export type ReleaseCategory = 'global_release' | 'us_only' | 'local_release';
