/**
 * Generated by '@kontent-ai/model-generator@6.1.0'
 *
 * ReleaseCategory
 * Id: 09b6a348-0f86-7a68-4af3-7cab9a5c60b7
 * Codename: releasecategory
 */
export type ReleaseCategory = 'global_release' | 'local_release' | 'us_only';
