import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.2.0'
 *
 * Page
 * Id: 2ef19f7d-5831-43f8-ad2f-892b3673316c
 * Codename: page
 */
export type Page = IContentItem<{
    /**
     * Content (modular_content)
     * Required: false
     * Id: f3e8106c-4d3f-4b8c-bbf6-e6830defef77
     * Codename: content
     */
    content: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Show in navigation (multiple_choice)
     * Required: false
     * Id: 7261cf38-c18a-4dcf-aa56-19f564b0a83f
     * Codename: show_in_navigation
     */
    show_in_navigation: Elements.MultipleChoiceElement;

    /**
     * Subpages (subpages)
     * Required: false
     * Id: 0483231c-adfd-4ea4-bec9-88216070a81c
     * Codename: subpages
     */
    subpages: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Title (text)
     * Required: false
     * Id: 08b34d36-7587-4de5-ae07-b8e8466f418a
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * URL (url_slug)
     * Required: false
     * Id: a0938e88-8b8a-497b-852f-59fcd9bb1321
     * Codename: url
     */
    url: Elements.UrlSlugElement;
}>;
