import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Category } from '../taxonomies/category';

/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Person
 * Id: 081a7b99-575d-473c-9cd0-67094803da73
 * Codename: person
 */
export type Person = IContentItem<{
    /**
     * Bio (rich_text)
     * Required: false
     * Id: 8e24b232-dfdd-4f4c-8e62-379baf194c24
     * Codename: bio
     */
    bio: Elements.RichTextElement;

    /**
     * Category (taxonomy)
     * Required: false
     * Id: 81ff1d64-f4f8-4cf4-bc1e-a076b554cd3d
     * Codename: category
     */
    category: Elements.TaxonomyElement<Category>;

    /**
     * custom element (custom)
     * Required: false
     * Id: 85fa4bd3-0445-466e-bb6f-8c3228ea12a6
     * Codename: custom_element
     */
    custom_element: Elements.CustomElement;

    /**
     * Date of Birth (date_time)
     * Required: false
     * Id: fd009675-1d52-4259-a72a-4c52808fbebd
     * Codename: date_of_birth
     */
    date_of_birth: Elements.DateTimeElement;

    /**
     * Favorite Number (number)
     * Required: false
     * Id: db98d495-49b5-4ab5-b08c-ef31fae3277d
     * Codename: favorite_number
     */
    favorite_number: Elements.NumberElement;

    /**
     * Friends (modular_content)
     * Required: false
     * Id: 7ccfe5f8-373f-440b-b622-4ba7867ec248
     * Codename: friends
     */
    friends: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Gender (multiple_choice)
     * Required: false
     * Id: da20aeac-83d4-4da2-b6f1-ab3395dcc922
     * Codename: gender
     */
    gender: Elements.MultipleChoiceElement;

    /**
     * Name and Surname (text)
     * Required: true
     * Id: d0726df3-7ca6-4183-bdc1-41c0fe573932
     * Codename: name_and_surname
     */
    name_and_surname: Elements.TextElement;

    /**
     * Profile Photo (asset)
     * Required: false
     * Id: 23ae3be4-aa8c-4bf3-8a30-4bb4d7a6fa71
     * Codename: profile_photo
     */
    profile_photo: Elements.AssetsElement;

    /**
     * URL slug (url_slug)
     * Required: false
     * Id: ea17615b-e0dc-4fba-8224-b8891ce8497c
     * Codename: url_slug
     */
    url_slug: Elements.UrlSlugElement;
}>;
