import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Repository
 * Id: c88be77c-83a6-4839-855f-66c28f624d1d
 * Codename: repository
 */
export type Repository = IContentItem<{
    /**
     * Description (custom)
     * Required: false
     * Id: 2ba28366-7c0c-4b20-893e-90920e903798
     * Codename: description
     */
    description: Elements.CustomElement;

    /**
     * Name (text)
     * Required: false
     * Id: ae29bcd9-a8dd-49c4-8a31-1becf790b4e9
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * URL (text)
     * Required: false
     * Id: ff86d6ab-5528-4737-8389-35b83f97f880
     * Codename: url
     */
    url: Elements.TextElement;
}>;
