import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Step
 * Id: c4b8e601-77f5-4535-b522-8b38db55873e
 * Codename: step
 */
export type Step = IContentItem<{
    /**
     * Text (rich_text)
     * Required: false
     * Id: 360eec57-77c0-4352-90be-fc86ecb1946a
     * Codename: text
     */
    text: Elements.RichTextElement;
}>;
