import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.0.3'
 *
 * Template - Category Page - 'Other' Categories
 * Id: 5c8fe7ea-0df6-42e0-a15f-0d96cfd8a4bd
 * Codename: template___category_page____other__categories
 */
export type TemplateCategoryPageOtherCategories = IContentItem<{
    /**
     * fefse (text)
     * Required: false
     * Id: e162e9eb-1e0d-49f9-b2aa-2f2d0b5c2df3
     * Codename: fefse
     */
    fefse: Elements.TextElement;
}>;
