import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Person } from './person';
import { type Session } from './session';

/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Training
 * Id: d4cf750f-61d3-4782-bf9c-b7184b7b2fc3
 * Codename: training
 */
export type Training = IContentItem<{
    /**
     * Author (modular_content)
     * Required: false
     * Id: 28082ed5-347f-4596-965c-5b05c4d4a50b
     * Codename: author
     */
    author: Elements.LinkedItemsElement<Person>;

    /**
     * Description (rich_text)
     * Required: false
     * Id: ee37d129-673f-459c-a94d-807e24de61f5
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Name (text)
     * Required: false
     * Id: 93f00d8b-ce52-4d26-96ae-4607a0438000
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * Sessions (modular_content)
     * Required: false
     * Id: b6e2b3f7-3d0a-4b8a-bbd5-2b1e256528cd
     * Codename: sessions
     */
    sessions: Elements.LinkedItemsElement<Session>;
}>;
