import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Website
 * Id: aeabe925-9221-4fb2-bc3a-2a91abc904fd
 * Codename: website
 */
export type Website = IContentItem<{
    /**
     * Description (rich_text)
     * Required: false
     * Id: 7ebea693-c2e5-4455-9242-e71832f24c87
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Name (text)
     * Required: false
     * Id: 7b9e7b9f-d6ba-4838-830b-d7fbb864ab4e
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * URL (text)
     * Required: false
     * Id: 15b01ff6-b05f-4a7f-8795-9ea6f9b7b997
     * Codename: url
     */
    url: Elements.TextElement;
}>;
