/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all codenames
 *
 * Type: Snippet
 */
export const snippetCodenames = [] as const;

/*
 * Type representing all codenames
 *
 * Type: Snippet
 */
export type SnippetCodenames = (typeof snippetCodenames)[number];

/*
 * Typeguard for codename
 *
 * Type: Snippet
 */
export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
	return typeof value === 'string' && (snippetCodenames as readonly string[]).includes(value);
}
