import { EnvironmentModels } from '@kontent-ai/management-sdk';
import { libMetadata } from '../meta/index.js';

export function commentsManager(addTimestamp: boolean) {
    const generatedBy = (): string => {
        if (addTimestamp) {
            return `Generated by '${libMetadata.name}@${libMetadata.version}' at '${new Date().toUTCString()}'`;
        }

        return `Generated by '${libMetadata.name}@${libMetadata.version}'`;
    };

    const wrapComment = (comment: string, opts?: { addGeneratedBy: boolean }): string => {
        if (opts?.addGeneratedBy) {
            return `/** \n * ${generatedBy()} ${comment} \n*/`;
        }
        return `/** \n * ${comment} \n*/`;
    };

    const environmentInfo = (
        environmentInfo: Readonly<EnvironmentModels.EnvironmentInformationModel>,
        opts?: { addGeneratedBy: boolean }
    ): string => {
        return wrapComment(
            `
* ${environmentInfo.name}
*  
* Environment: ${environmentInfo.environment}
* Id: ${environmentInfo.id}`,
            opts
        );
    };

    return {
        wrapComment,
        environmentInfo
    };
}
