import { EnvironmentModels } from '@kontent-ai/management-sdk';
import { libMetadata } from '../meta/index.js';
import { toSafeString } from '../core/index.js';

export function commentsManager() {
    const wrapComment = (comment: string): string => {
        return `/** \n * ${comment} \n*/`;
    };

    const getEnvironmentInfoComment = (data: {
        addTimestamp?: boolean;
        environmentInfo: Readonly<EnvironmentModels.EnvironmentInformationModel>;
    }): string => {
        return `
/** 
* This file has been auto-generated by '${libMetadata.name}@${libMetadata.version}'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: ${toSafeString(data.environmentInfo.name)}
* Environment: ${toSafeString(data.environmentInfo.environment)}
* Id: ${data.environmentInfo.id}${data.addTimestamp ? `\n* Generated: ${new Date().toLocaleString()}` : ''}
* 
* -------------------------------------------------------------------------------
**/`;
    };

    return {
        wrapComment,
        getEnvironmentInfoComment
    };
}
