/**
 * Generated by '@kontent-ai/model-generator@5.4.1' at 'Thu, 01 Sep 2022 11:35:49 GMT'
 *
 * Project name: Import source (Movie DB test)
 * Environment: Production
 * Project Id: cdbf5823-cbec-010d-f4c3-0411eee31c0e
 */
export const assetFolders = {};
