/**
 * Generated by '@kontent-ai/model-generator@5.6.0' at 'Thu, 15 Sep 2022 09:52:52 GMT'
 *
 * Project name: Import source (Movie DB test)
 * Environment: Production
 * Project Id: cdbf5823-cbec-010d-f4c3-0411eee31c0e
 */
export const assetFolders = {};
