/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Mon, 09 May 2022 09:19:22 GMT'
 *
 * Project name: Movie Database
 * Environment: Production
 * Project Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 */
export const collections = {
  /**
   * Default
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
};
