/**
 * Generated by '@kontent-ai/model-generator@5.6.0' at 'Thu, 15 Sep 2022 09:52:52 GMT'
 *
 * Project name: Import source (Movie DB test)
 * Environment: Production
 * Project Id: cdbf5823-cbec-010d-f4c3-0411eee31c0e
 */
export const contentTypeSnippets = {
  /**
   * Test
   * Last modified: Thu Sep 15 2022 11:52:42 GMT+0200 (Central European Summer Time)
   */
  test: {
    codename: 'test',
    id: '1499b802-b6ec-45d4-84d7-9e05ee379c06',
    externalId: undefined,
    name: 'Test',
    elements: {
      /**
       * fefe (asset)
       */
      test__fefe: {
        codename: 'test__fefe',
        id: '27e67a4c-fe1c-43d2-a9a2-192b0b5db68b',
        externalId: undefined,
        name: 'fefe',
        required: false,
        type: 'asset',
      },

      /**
       * fasfefase (text)
       */
      test__fasfefase: {
        codename: 'test__fasfefase',
        id: '44b1f309-5847-4fd3-b350-9fdcbf3c2008',
        externalId: undefined,
        name: 'fasfefase',
        required: false,
        type: 'text',
      },
    },
  },
};
