/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */
import { person } from './content-types/person';
import { repository } from './content-types/repository';
import { session } from './content-types/session';
import { step } from './content-types/step';
import { training } from './content-types/training';
import { website } from './content-types/website';
export const contentTypes = {
    /**
     * Person
     */
    person,
    /**
     * Repository
     */
    repository,
    /**
     * Session
     */
    session,
    /**
     * Step
     */
    step,
    /**
     * Training
     */
    training,
    /**
     * Website
     */
    website
};
