/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 * Movie Database
 *
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 */
export const contentTypeSnippets = {} as const;
