/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */
export const contentTypeSnippets = {} as const;
