/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Mon, 09 May 2022 14:00:06 GMT'
 *
 * Project name: Movie Database
 * Environment: Production
 * Project Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 */
export const languages = {
  /**
   * English
   * Is Active: true
   * Is Default: true
   * Fallback language Id: 00000000-0000-0000-0000-000000000000
   */
  en: {
    codename: 'en',
    id: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'English',
  },

  /**
   * cz
   * Is Active: true
   * Is Default: false
   * Fallback language Id: 00000000-0000-0000-0000-000000000000
   */
  cz: {
    codename: 'cz',
    id: '41ccb26f-ceab-04d0-6ffa-9c7c5358aa8f',
    externalId: undefined,
    name: 'cz',
  },

  /**
   * German
   * Is Active: false
   * Is Default: false
   * Fallback language Id: 00000000-0000-0000-0000-000000000000
   */
  german: {
    codename: 'German',
    id: '14f7bcc0-4fd6-4b77-8c22-70e5ccfdae1d',
    externalId: undefined,
    name: 'German',
  },
};
