/**
 * Generated by '@kontent-ai/model-generator@7.0.3'
 *
 * Project name: Movie Database
 * Environment: Production
 * Environment Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 */
export const languages = {
    /**
     * cz
     */
    cz: {
        codename: 'cz',
        id: '41ccb26f-ceab-04d0-6ffa-9c7c5358aa8f',
        isActive: true,
        isDefault: false,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'cz'
    },

    /**
     * English
     */
    en: {
        codename: 'en',
        id: '00000000-0000-0000-0000-000000000000',
        isActive: true,
        isDefault: true,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'English'
    },

    /**
     * German
     */
    german: {
        codename: 'German',
        id: '14f7bcc0-4fd6-4b77-8c22-70e5ccfdae1d',
        isActive: false,
        isDefault: false,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'German'
    }
} as const;
