/**
 * Generated by '@kontent-ai/model-generator@5.3.0' at 'Mon, 01 Aug 2022 09:20:39 GMT'
 *
 * Project name: Import source (Movie DB test)
 * Environment: Production
 * Project Id: cdbf5823-cbec-010d-f4c3-0411eee31c0e
 */
export const languages = {
  /**
   * English
   */
  en: {
    codename: 'en',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'English',
  },

  /**
   * cz
   */
  cz: {
    codename: 'cz',
    id: '41ccb26f-ceab-04d0-6ffa-9c7c5358aa8f',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'cz',
  },

  /**
   * German
   */
  german: {
    codename: 'German',
    id: '14f7bcc0-4fd6-4b77-8c22-70e5ccfdae1d',
    isActive: false,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'German',
  },
};
