/**
 * Generated by '@kontent-ai/model-generator@5.2.0' at 'Thu, 28 Jul 2022 10:05:53 GMT'
 *
 * Project name: Import source (Movie DB test)
 * Environment: Production
 * Project Id: cdbf5823-cbec-010d-f4c3-0411eee31c0e
 */
export const roles = {
  /**
   * Developer
   */
  developer: {
    codename: undefined,
    id: 'f797bab5-e088-42ec-be34-00bf23e901a9',
    name: 'Developer',
  },

  /**
   * Content contributor
   */
  contentContributor: {
    codename: undefined,
    id: 'c57be24b-0bf8-42cc-ab39-20b9bcd8f968',
    name: 'Content contributor',
  },

  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: '39aa137d-cfce-4443-86a0-81423b4ab3b3',
    name: 'Project manager',
  },

  /**
   * Reviewer
   */
  reviewer: {
    codename: undefined,
    id: 'bd658d5a-21fc-40e0-96b2-f1ac4736e478',
    name: 'Reviewer',
  },
};
