/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */
export const roles = {
    /**
     * Content Developer
     */
    contentDeveloper: {
        codename: undefined,
        id: '591072ce-fcad-43fd-9735-f161fa86eb96',
        name: 'Content Developer'
    },

    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: '0fa2d43d-a83e-4d0b-bfd7-6d73d0714832',
        name: 'Project manager'
    }
} as const;
