/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */
export const taxonomies = {
    /**
     * Category
     */
    category: {
        codename: 'category',
        id: 'f9cfab9c-3a44-462d-8d6e-4679c72c4aae',
        externalId: undefined,
        name: 'Category',
        terms: {
            first: {
                codename: 'first',
                id: 'f2950872-fcd9-4003-8fc0-07b3bd8a743f',
                externalId: undefined,
                name: 'First',
                terms: {
                    sub_first: {
                        codename: 'sub_first',
                        id: 'a099c015-5a15-408d-bad5-a5aff5cb5611',
                        externalId: undefined,
                        name: 'Sub-first',
                        terms: {
                            sub_sub_first: {
                                codename: 'sub_sub_first',
                                id: '54da8e8c-4aa5-4ab6-b56a-7c52bc9ebb9d',
                                externalId: undefined,
                                name: 'Sub-sub-first',
                                terms: {}
                            }
                        }
                    }
                }
            },
            second: {
                codename: 'second',
                id: '3344bef2-fe49-41ba-af87-fc78b2ce10d7',
                externalId: undefined,
                name: 'Second',
                terms: {
                    sub_second: {
                        codename: 'sub_second',
                        id: 'f3bf0352-0283-44a7-8d7c-4dca30a8e220',
                        externalId: undefined,
                        name: 'Sub-second',
                        terms: {}
                    }
                }
            },
            y: {
                codename: 'y',
                id: '31ded409-4b06-4145-b413-bfec492aa075',
                externalId: undefined,
                name: 'y',
                terms: {}
            }
        }
    }
} as const;
