/**
 * Generated by '@kontent-ai/model-generator@5.1.0' at 'Thu, 21 Jul 2022 12:39:28 GMT'
 *
 * Project name: Movie Database
 * Environment: Production
 * Project Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 */
export const taxonomies = {
  /**
   * MovieType
   */
  movietype: {
    codename: 'movietype',
    id: '365a17e6-1929-27ab-9f67-a9273c846717',
    externalId: undefined,
    name: 'MovieType',
    terms: {
      student: {
        codename: 'student',
        id: 'b107e12c-124d-705f-1029-c0dfdd0b2438',
        externalId: undefined,
        name: 'Student',
        terms: {},
      },
      film: {
        codename: 'film',
        id: '5a2a1927-41a4-294f-5d89-cf0cc045e943',
        externalId: undefined,
        name: 'Film',
        terms: {
          tv: {
            codename: 'tv',
            id: '47511b09-6c39-fa04-ff59-7c47551e827f',
            externalId: undefined,
            name: 'TV',
            terms: {},
          },
          blockbuster: {
            codename: 'blockbuster',
            id: '875a4657-1dcd-0415-cb3a-892078f5991a',
            externalId: undefined,
            name: 'Blockbuster',
            terms: {},
          },
          cinema_only: {
            codename: 'cinema_only',
            id: 'e15c4e32-ab7c-57a2-1b66-d8e3566a1dd2',
            externalId: undefined,
            name: 'Cinema only',
            terms: {},
          },
        },
      },
    },
  },

  /**
   * ReleaseCategory
   */
  releasecategory: {
    codename: 'releasecategory',
    id: '09b6a348-0f86-7a68-4af3-7cab9a5c60b7',
    externalId: undefined,
    name: 'ReleaseCategory',
    terms: {
      global_release: {
        codename: 'global_release',
        id: '4acaf439-9f3a-f34a-6211-d3fc6ec7152e',
        externalId: undefined,
        name: 'Global release',
        terms: {},
      },
      us_only: {
        codename: 'us_only',
        id: 'b03d990a-55a9-601e-dd5c-aa2edc8698ca',
        externalId: undefined,
        name: 'US only',
        terms: {},
      },
      local_release: {
        codename: 'local_release',
        id: '37e55484-f0dc-14eb-bf2a-b0293a0d1b1f',
        externalId: undefined,
        name: 'Local release',
        terms: {},
      },
    },
  },
};
