/**
 * Generated by '@kontent-ai/model-generator@6.3.1'
 *
 * Project name: Import source  Movie DB test
 * Environment: Production
 * Environment Id: cdbf5823-cbec-010d-f4c3-0411eee31c0e
 */
export const webhooks = {} as const;
