/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Project name: Movie Database
 * Environment: Production
 * Environment Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 */
export const webhooks = {} as const;
