/**
 * Generated by '@kontent-ai/model-generator@5.7.0' at 'Thu, 06 Oct 2022 08:31:15 GMT'
 *
 * Project name: Import source (Movie DB test)
 * Environment: Production
 * Project Id: cdbf5823-cbec-010d-f4c3-0411eee31c0e
 */
export const webhooks = {};
