/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Mon, 09 May 2022 14:00:06 GMT'
 *
 * Project name: Movie Database
 * Environment: Production
 * Project Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 */
export const workflows = {
  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: f05b8a85-c6cc-429a-ac6d-21d5edd268fe
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
};
