/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Complex Project
 * Environment: Production
 * Environment Id: 09fc0115-dd4d-00c7-5bd9-5f73836aee81
 */
export const workflows = {
    /**
     * Default
     * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
     * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
     */
    default: {
        codename: 'default',
        id: '00000000-0000-0000-0000-000000000000',
        name: 'Default',
        steps: {
            archived: {
                name: 'Archived',
                codename: 'archived',
                id: '7a535a69-ad34-47f8-806a-def1fdf4d391'
            },
            published: {
                name: 'Published',
                codename: 'published',
                id: 'c199950d-99f0-4983-b711-6c4c91624b22'
            },
            scheduled: {
                name: 'Scheduled',
                codename: 'scheduled',
                id: '9d2b0228-4d0d-4c23-8b49-01a698857709'
            },
            draft: {
                name: 'Draft',
                codename: 'draft',
                id: 'e7f6d2c6-55c9-4419-af35-25fe3e00d8d0'
            }
        }
    }
} as const;
