/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@{{version}}'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

export * from "./contentTypes/actor.generated.js"
export * from "./contentTypes/movie.generated.js"
export * from "./environment/environment.generated.js"
export * from "./migration.generated.js"
