/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-3'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Movie Database
 * Environment: Production
 * Id: da5abe9f-fdad-4168-97cd-b3464be2ccb9
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all codenames
 *
 * Type: Type
 */
export const typeCodenames = ['actor', 'movie'] as const;

/*
 * Type representing all codenames
 *
 * Type: Type
 */
export type TypeCodenames = (typeof typeCodenames)[number];

/*
 * Typeguard for codename
 *
 * Type: Type
 */
export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
	return typeof value === 'string' && (typeCodenames as readonly string[]).includes(value);
}
